export const lexmeaGesetze = {
	AAG: { title: "Aufwendungsausgleichsgesetz" },
	ARegV: { title: "Anreizregulierungsverordnung" },
	ApoG: { title: "Apothekengesetz" },
	AFGBV: { title: "Autonome-Fahrzeuge-Genehmigungs-und-Betriebs-Verordnung" },
	"Alt\u00f6lV": { title: "Alt\u00f6lverordnung" },
	AbwV: { title: "Abwasserverordnung" },
	AMG: { title: "Arzneimittelgesetz" },
	"Artikel 10-Gesetz": {
		title: "Gesetz zur Beschr\u00e4nkung des Brief-, Post- und Fernmeldegeheimnisses",
	},
	ArbGG: { title: "Arbeitsgerichtsgesetz" },
	AbfVerbrG: { title: "Abfallverbringungsgesetz" },
	"Artikel 115-Gesetz": {
		title: "Gesetz zur Ausf\u00fchrung von Artikel 115 des Grundgesetzes",
	},
	AFWoG: {
		title: "Gesetz \u00fcber den Abbau der Fehlsubventionierung im Wohnungswesen",
	},
	AdVermiG: { title: "Adoptionsvermittlungsgesetz" },
	ASiG: { title: "Arbeitssicherheitsgesetz" },
	AnfG: { title: "Anfechtungsgesetz" },
	AGG: { title: "Allgemeines Gleichbehandlungsgesetz" },
	ArbnErfG: { title: "Gesetz \u00fcber Arbeitnehmererfindungen" },
	AsylbLG: { title: "Asylbewerberleistungsgesetz" },
	AnlEntG: { title: "Anlegerentsch\u00e4digungsgesetz" },
	AbgG: { title: "Abgeordnetengesetz" },
	AsylG: { title: "Asylgesetz" },
	AktG: { title: "Aktiengesetz" },
	ArbPlSchG: { title: "Arbeitsplatzschutzgesetz" },
	AnzV: { title: "Anzeigenverordnung" },
	AdWirkG: { title: "Adoptionswirkungsgesetz" },
	AbrStV: { title: "Abrechnungsstellenverordnung" },
	ArbSchG: { title: "Arbeitsschutzgesetz" },
	"Ad\u00dcbAG": {
		title: "Adoptions\u00fcbereinkommens-Ausf\u00fchrungsgesetz",
	},
	AltfahrzeugV: { title: "Altfahrzeug-Verordnung" },
	AO: { title: "Abgabenordnung" },
	AbschlagsV: {
		title: "Verordnung \u00fcber Abschlagszahlungen bei Bautr\u00e4gervertr\u00e4gen",
	},
	ArbZG: { title: "Arbeitszeitgesetz" },
	AltZertG: { title: "Altersvorsorgevertr\u00e4ge-Zertifizierungsgesetz" },
	AbwAG: { title: "Abwasserabgabengesetz" },
	AEntG: { title: "Arbeitnehmer-Entsendegesetz" },
	AsylZBV: { title: "Asylzust\u00e4ndigkeitsbestimmungsVO" },
	AtG: { title: "Atomgesetz" },
	"\u00c4rzte-ZV": {
		title: "Zulassungsverordnung f\u00fcr Vertrags\u00e4rzte",
	},
	ATZV: { title: "Altersteilzeitzuschlagsverordnung" },
	"BAf\u00f6G": { title: "Bundesausbildungsf\u00f6rderungsgesetz" },
	AWaffV: { title: "Allgemeine Waffengesetz-Verordnung" },
	AufenthG: { title: "Aufenthaltsgesetz" },
	BBankG: { title: "Gesetz \u00fcber die Deutsche Bundesbank" },
	BauFordSiG: { title: "Bauforderungssicherungsgesetz" },
	AufenthV: { title: "Aufenthaltsverordnung" },
	BArtSchV: { title: "Bundesartenschutzverordnung" },
	BBesG: { title: "Bundesbesoldungsgesetz" },
	AWG: { title: "Au\u00dfenwirtschaftsgesetz" },
	AEUV: { title: "Vertrag über die Arbeitsweise der Europäischen Union" },
	BAStrlSchG: {
		title: "Gesetz \u00fcber die Errichtung eines Bundesamtes f\u00fcr Strahlenschutz",
	},
	BauGB: { title: "Baugesetzbuch" },
	AUG: { title: "Auslandsunterhaltsgesetz" },
	BBG: { title: "Bundesbeamtengesetz" },
	BattG: { title: "Batteriegesetz" },
	BBodSchV: { title: "Bundes-Bodenschutz- und Altlastenverordnung" },
	AWV: { title: "Au\u00dfenwirtschaftsverordnung" },
	BauNVO: { title: "Baunutzungsverordnung" },
	BBPlG: { title: "Bundesbedarfsplangesetz" },
	BBhV: { title: "Bundesbeihilfeverordnung" },
	BATZV: { title: "Beamtenaltersteilzeitverordnung" },
	AZRG: { title: "AZR-Gesetz" },
	BDG: { title: "Bundesdisziplinargesetz" },
	BBiG: { title: "Berufsbildungsgesetz" },
	BauPG: { title: "Bauproduktengesetz" },
	"BeamtV\u00dcV": { title: "Beamtenversorgungs-\u00dcbergangsverordnung" },
	AZV: { title: "Arbeitszeitverordnung" },
	BBodSchG: { title: "Bundes-Bodenschutzgesetz" },
	BauSparkG: { title: "Gesetz \u00fcber Bausparkassen" },
	BedGgstV: { title: "Bedarfsgegenst\u00e4ndeverordnung" },
	BDSG: { title: "Bundesdatenschutzgesetz" },
	"A\u00dcG": { title: "Arbeitnehmer\u00fcberlassungsgesetz" },
	BeamtStG: { title: "Beamtenstatusgesetz" },
	BeschG: { title: "Beschussgesetz" },
	BausparkV: { title: "Bausparkassen-Verordnung" },
	BEEG: { title: "Bundeselterngeld- und Elternzeitgesetz" },
	BeschussV: { title: "Beschussverordnung" },
	BetrVG: { title: "Betriebsverfassungsgesetz" },
	BeamtVG: { title: "Beamtenversorgungsgesetz" },
	BeschV: { title: "Besch\u00e4ftigungsverordnung" },
	BefBezG: {
		title: "Gesetz \u00fcber befriedete Bezirke f\u00fcr Verfassungsorgane des Bundes",
	},
	BKatV: { title: "Bu\u00dfgeldkatalog-Verordnung" },
	BeurkG: { title: "Beurkundungsgesetz" },
	BGleiG: { title: "Bundesgleichstellungsgesetz" },
	"Bes\u00dcG": { title: "Besoldungs\u00fcberleitungsgesetz" },
	BEHG: { title: "Brennstoffemissionshandelsgesetz" },
	BKGG: { title: "Bundeskindergeldgesetz" },
	BNatSchG: { title: "Bundesnaturschutzgesetz" },
	BetrAVG: { title: "Betriebsrentengesetz" },
	BNDG: { title: "BND-Gesetz" },
	BerHG: { title: "Beratungshilfegesetz" },
	BLBV: { title: "Bundesleistungsbesoldungsverordnung" },
	BetrKV: { title: "Betriebskostenverordnung" },
	BewG: { title: "Bewertungsgesetz" },
	BHO: { title: "Bundeshaushaltsordnung" },
	BLV: { title: "Bundeslaufbahnverordnung" },
	BNotO: { title: "Bundesnotarordnung" },
	BfkEG: {
		title: "Gesetz \u00fcber die Errichtung eines Bundesamtes f\u00fcr die Sicherheit der nuklearen Entsorgung",
	},
	BImSchG: { title: "Bundes-Immissionsschutzgesetz" },
	BMG: { title: "Bundesmeldegesetz" },
	BfNatSchG: {
		title: "Gesetz \u00fcber die Errichtung eines Bundesamtes f\u00fcr Naturschutz",
	},
	BNV: { title: "Bundesnebent\u00e4tigkeitsverordnung" },
	BMVergV: { title: "Bundesmehrarbeitsverg\u00fctungsverordnung" },
	BiomasseV: { title: "Biomasseverordnung" },
	"BSI-KritisV": { title: "BSI-Kritisverordnung" },
	BPersVG: { title: "Bundespersonalvertretungsgesetz" },
	BPolG: { title: "Bundespolizeigesetz" },
	BSIG: { title: "BSI-Gesetz" },
	BJagdG: { title: "Bundesjagdgesetz" },
	BGB: { title: "B\u00fcrgerliches Gesetzbuch" },
	BPflV: { title: "Bundespflegesatzverordnung" },
	BUKG: { title: "Bundesumzugskostengesetz" },
	BUrlG: { title: "Bundesurlaubsgesetz" },
	BKAG: { title: "Bundeskriminalamtgesetz" },
	BRAO: { title: "Bundesrechtsanwaltsordnung" },
	"BTGO1980Anl 2a": {
		title: "Verhaltenskodex f\u00fcr Interessenvertreterinnen und Interessenvertreter im Rahmen des Lobbyregistergesetzes (Anlage 2a der Gesch\u00e4ftsordnung des Deutschen Bundestages, BGBl. I 1980, 1237)",
	},
	BtMG: { title: "Bet\u00e4ubungsmittelgesetz" },
	BVerfGG: { title: "Bundesverfassungsgerichtsgesetz" },
	BRKG: { title: "Bundesreisekostengesetz" },
	BtMVV: { title: "Bet\u00e4ubungsmittel-Verschreibungsverordnung" },
	BZRG: { title: "Bundeszentralregistergesetz" },
	BWahlG: { title: "Bundeswahlgesetz" },
	BVerfSchG: { title: "Bundesverfassungsschutzgesetz" },
	BtOG: { title: "Betreuungsorganisationsgesetz" },
	"B\u00c4O": { title: "Bundes\u00e4rzteordnung" },
	BRRG: { title: "Beamtenrechtsrahmengesetz" },
	CsgG: { title: "Carsharinggesetz" },
	BVersG: { title: "Versammlungsgesetz" },
	DBUStiftG: {
		title: 'Gesetz zur Errichtung einer Stiftung "Deutsche Bundesstiftung Umwelt"',
	},
	"B\u00f6rsG": { title: "B\u00f6rsengesetz" },
	BWaldG: { title: "Bundeswaldgesetz" },
	DepotG: { title: "Depotgesetz" },
	BVFG: { title: "Bundesvertriebenengesetz" },
	ChemG: { title: "Chemikaliengesetz" },
	BwBBG: { title: "Bundeswehrbeschaffungsbeschleunigungsgesetz" },
	DesignG: { title: "Designgesetz" },
	BwFinSVermG: {
		title: "Bundeswehrfinanzierungs- und sonderverm\u00f6gensgesetz",
	},
	"D\u00fcngG": { title: "D\u00fcngegesetz" },
	BWO: { title: "Bundeswahlordnung" },
	EGAO: { title: "Einf\u00fchrungsgesetz zur Abgabenordnung" },
	DNG: { title: "Datennutzungsgesetz" },
	EBRG: { title: "Europ\u00e4ische Betriebsr\u00e4te-Gesetz" },
	EGGmbHG: { title: "GmbHG-Einf\u00fchrungsgesetz" },
	CO2KostAufG: { title: "Kohlendioxidkostenaufteilungsgesetz" },
	BzBlG: { title: "Benzinbleigesetz" },
	EGGVG: { title: "Einf\u00fchrungsgesetz zum Gerichtsverfassungsgesetz" },
	"EDL-G": { title: "Energiedienstleistungsgesetz" },
	DRiG: { title: "Deutsches Richtergesetz" },
	EGHGB: { title: "Einf\u00fchrungsgesetz zum Handelsgesetzbuch" },
	EEG: { title: "Erneuerbare-Energien-Gesetz" },
	EGStPO: { title: "Einf\u00fchrungsgesetz zur Strafprozessordnung" },
	DrittelbG: { title: "Drittelbeteiligungsgesetz" },
	DSGVO: { title: "Datenschutz-Grundverordnung" },
	DMA: { title: "Digital Markets Act" },
	DSA: { title: "Digital Services Act" },
	DGA: { title: "Digital Governance Act" },
	EGovG: { title: "E-Government-Gesetz" },
	EEV: { title: "Erneuerbare-Energien-Verordnung" },
	EMASPrivilegV: { title: "EMAS-Privilegierungs-Verordnung" },
	EGRDG: { title: "Einf\u00fchrungsgesetz zum Rechtsdienstleistungsgesetz" },
	EmoG: { title: "Elektromobilit\u00e4tsgesetz" },
	EGAktG: { title: "Einf\u00fchrungsgesetz zum Aktiengesetz" },
	EGVVG: { title: "Einf\u00fchrungsgesetz zum Versicherungsvertragsgesetz" },
	EnStatG: { title: "Energiestatistikgesetz" },
	EnEfG: { title: "Energieeffizienzgesetz" },
	EinbTestV: { title: "Einb\u00fcrgerungstestverordnung" },
	EnFG: { title: "Energiefinanzierungsgesetz" },
	EnSTransV: {
		title: "Energiesteuer- und Stromsteuer-Transparenzverordnung",
	},
	EinSiG: { title: "Einlagensicherungsgesetz" },
	EnLAG: { title: "Energieleitungsausbaugesetz" },
	EntgFG: { title: "Entgeltfortzahlungsgesetz" },
	EntgTranspG: { title: "Entgelttransparenzgesetz" },
	ErbbauRG: { title: "Erbbaurechtsgesetz" },
	EnSiG: { title: "Energiesicherungsgesetz" },
	eKFV: { title: "Elektrokleinstfahrzeuge-Verordnung" },
	EnWG: { title: "Energiewirtschaftsgesetz" },
	ErbStDV: { title: "Erbschaftsteuer-Durchf\u00fchrungsverordnung" },
	EUAHiG: { title: "EU-Amtshilfegesetz" },
	ElektroG: { title: "Elektro- und Elektronikger\u00e4tegesetz" },
	EUStBV: { title: "Einfuhrumsatzsteuer-Befreiungsverordnung" },
	EPPSG: { title: "Studierenden-Energiepreispauschalengesetz" },
	ErbStG: { title: "Erbschaftsteuer- und Schenkungsteuergesetz" },
	ESchG: { title: "Embryonenschutzgesetz" },
	EWKFondsG: { title: "Einwegkunststofffondsgesetz" },
	EStG: { title: "Einkommensteuergesetz" },
	EuPAG: {
		title: "Gesetz \u00fcber die T\u00e4tigkeit europ\u00e4ischer Patentanw\u00e4lte in Deutschland",
	},
	FinaRisikoV: {
		title: "Finanz- und Risikotragf\u00e4higkeitsinformationenverordnung",
	},
	EuWG: { title: "Europawahlgesetz" },
	EUZBBG: {
		title: "Gesetz \u00fcber die Zusammenarbeit von Bundesregierung und Deutschem Bundestag in Angelegenheiten der Europ\u00e4ischen Union",
	},
	"EU-EnergieKBG": { title: "EU-Energiekrisenbeitragsgesetz" },
	EWPBG: { title: "Erdgas-W\u00e4rme-Preisbremsengesetz" },
	EuRAG: {
		title: "Gesetz \u00fcber die T\u00e4tigkeit europ\u00e4ischer Rechtsanw\u00e4lte in Deutschland",
	},
	FinDAG: { title: "Finanzdienstleistungsaufsichtsgesetz" },
	EUZBLG: {
		title: "Gesetz \u00fcber die Zusammenarbeit von Bund und L\u00e4ndern in Angelegenheiten der Europ\u00e4ischen Union",
	},
	FKAG: { title: "Finanzkonglomerate-Aufsichtsgesetz" },
	eWpG: { title: "Gesetz \u00fcber elektronische Wertpapiere" },
	EUrlV: { title: "Erholungsurlaubsverordnung" },
	EVPG: { title: "Energieverbrauchsrelevante-Produkte-Gesetz" },
	EUV: { title: "Vertrag zur Europ\u00e4ischen Union" },
	FlG: { title: "Fleischgesetz" },
	FMStBG: { title: "Wirtschaftsstabilisierungsbeschleunigungsgesetz" },
	FamFG: {
		title: "Gesetz \u00fcber das Verfahren in Familiensachen und in den Angelegenheiten der freiwilligen Gerichtsbarkeit",
	},
	FlugDaG: { title: "Fluggastdatengesetz" },
	FPfZG: { title: "Familienpflegezeitgesetz" },
	FMSAKostV: { title: "FMSA-Kostenverordnung" },
	FeV: { title: "Fahrerlaubnis-Verordnung" },
	"Freiz\u00fcgG/EU": { title: "Freiz\u00fcgigkeitsgesetz/EU" },
	GastG: { title: "Gastst\u00e4ttengesetz" },
	FuAG: { title: "Funkanlagengesetz" },
	FGO: { title: "Finanzgerichtsordnung" },
	GeschGehG: { title: "Gesetz zum Schutz von Gesch\u00e4ftsgeheimnissen" },
	FzgLiefgMeldV: { title: "Fahrzeuglieferungs-Meldepflichtverordnung" },
	GBO: { title: "Grundbuchordnung" },
	GesRV: { title: "Gesellschaftsregisterverordnung" },
	FZV: { title: "Fahrzeug-Zulassungsverordnung" },
	GEIG: { title: "Geb\u00e4ude-Elektromobilit\u00e4tsinfrastruktur-Gesetz" },
	GewO: { title: "Gewerbeordnung" },
	GbV: { title: "Gefahrgutbeauftragtenverordnung" },
	GDolmG: { title: "Gerichtsdolmetschergesetz" },
	GewSchG: { title: "Gewaltschutzgesetz" },
	GenDG: { title: "Gendiagnostikgesetz" },
	GGV: { title: "Geb\u00e4udegrundbuchverf\u00fcgung" },
	GebrMG: { title: "Gebrauchsmustergesetz" },
	GewStG: { title: "Gewerbesteuergesetz" },
	GOBT: { title: "Gesch\u00e4ftsordnung des Deutschen Bundestages" },
	GG: { title: "Grundgesetz f\u00fcr die Bundesrepublik Deutschland" },
	GIGV: { title: "IOP-Governance-Verordnung" },
	GEG: { title: "Geb\u00e4udeenergiegesetz" },
	GOZ: { title: "Geb\u00fchrenordnung f\u00fcr Zahn\u00e4rzte" },
	GKG: { title: "Gerichtskostengesetz" },
	"GO\u00c4": { title: "Geb\u00fchrenordnung f\u00fcr \u00c4rzte" },
	"GenG": { title: "Genossenschaftsgesetz" },
	"GVG": { title: "Gerichtsverfassungsgesetz" },
	"GrCH": { title: "Grundrechtecharta der Europäischen Union" },
	"HdlKlG": { title: "Handelsklassengesetz" },
	"GmbHG": {
		title: "Gesetz betreffend die Gesellschaften mit beschränkter Haftung",
	},
	GroMiKV: { title: "Gro\u00dfkredit- und Millionenkreditverordnung" },
	GWB: { title: "Gesetz gegen Wettbewerbsbeschr\u00e4nkungen" },
	HeilprG: { title: "Heilpraktikergesetz" },
	"HeilprGDV 1": {
		title: "Erste Heilpraktikergesetz-Durchf\u00fchrungsverordnung",
	},
	GrStG: { title: "Grundsteuergesetz" },
	GwG: { title: "Geldw\u00e4schegesetz" },
	GNotKG: { title: "Gerichts- und Notarkostengesetz" },
	GenTG: { title: "Gentechnikgesetz" },
	HeizkostenV: { title: "Verordnung \u00fcber Heizkostenabrechnung" },
	HaftPflG: { title: "Haftpflichtgesetz" },
	GOBRat: { title: "Gesch\u00e4ftsordnung des Bundesrates" },
	HeizkZuschG: { title: "Heizkostenzuschussgesetz" },
	HAG: { title: "Heimarbeitsgesetz" },
	GeoZG: { title: "Geodatenzugangsgesetz" },
	HinSchG: { title: "Hinweisgeberschutzgesetz" },
	HalblSchG: { title: "Halbleiterschutzgesetz" },
	HGB: { title: "Handelsgesetzbuch" },
	HkNRG: { title: "Herkunftsnachweisregistergesetz" },
	HOAI: { title: "Honorarordnung f\u00fcr Architekten und Ingenieure" },
	InsO: { title: "Insolvenzordnung" },
	HRV: { title: "Handelsregisterverordnung" },
	IntVG: { title: "Integrationsverantwortungsgesetz" },
	InsStatG: { title: "Insolvenzstatistikgesetz" },
	HWG: { title: "Heilmittelwerbegesetz" },
	JGG: { title: "Jugendgerichtsgesetz" },
	InstitutsVergV: { title: "Institutsverg\u00fctungsverordnung" },
	IRG: {
		title: "Gesetz \u00fcber die internationale Rechtshilfe in Strafsachen",
	},
	JuSchG: { title: "Jugendschutzgesetz" },
	HwO: { title: "Handwerksordnung" },
	IDNrG: { title: "Identifikationsnummerngesetz" },
	IntFamRVG: { title: "Internationales Familienrechtsverfahrensgesetz" },
	JVEG: { title: "Justizverg\u00fctungs- und -entsch\u00e4digungsgesetz" },
	IVSG: { title: "Intelligente Verkehrssysteme Gesetz" },
	JVKostG: { title: "Justizverwaltungskostengesetz" },
	IFG: { title: "Informationsfreiheitsgesetz" },
	IntV: { title: "Integrationskursverordnung" },
	JAktAV: { title: "Justizaktenaufbewahrungsverordnung" },
	KAGB: { title: "Kapitalanlagegesetzbuch" },
	KCanG: { title: "Konsumcannabisgesetz" },
	IfSG: { title: "Infektionsschutzgesetz" },
	JArbSchG: { title: "Jugendarbeitsschutzgesetz" },
	KapMuG: { title: "Kapitalanleger-Musterverfahrensgesetz" },
	KErzG: { title: "Gesetz \u00fcber die religi\u00f6se Kindererziehung" },
	InhKontrollV: { title: "Inhaberkontrollverordnung" },
	KraftNAV: { title: "Kraftwerks-Netzanschlussverordnung" },
	KfzPflVV: { title: "Kraftfahrzeug-Pflichtversicherungsverordnung" },
	KHEntgG: { title: "Krankenhausentgeltgesetz" },
	KrWaffKontrG: { title: "Kriegswaffenkontrollgesetz" },
	"KrWaffKontrGDV 1": {
		title: "Erste Kriegswaffenkontrollgesetz-Durchf\u00fchrungsverordnung",
	},
	KryptoWTransferV: { title: "Kryptowertetransferverordnung" },
	KunstUrhG: { title: "Kunsturhebergesetz" },
	"KrWaffKontrGDV 2": {
		title: "Zweite Kriegswaffenkontrollgesetz-Durchf\u00fchrungsverordnung",
	},
	KVBG: { title: "Kohleverstromungsbeendigungsgesetz" },
	KrZwMG: { title: "Kreditzweitmarktgesetz" },
	KHG: { title: "Krankenhausfinanzierungsgesetz" },
	KWMV: { title: "Kriegswaffenmeldeverordnung" },
	KonzVgV: { title: "Konzessionsvergabeverordnung" },
	KWG: { title: "Kreditwesengesetz" },
	LBAV: { title: "Laufbahnbef\u00e4higungsanerkennungsverordnung" },
	KrWaffUnbrUmgV: {
		title: "Kriegswaffenunbrauchbarmachungs- und -umgangsverordnung",
	},
	LFGB: { title: "Lebensmittel- und Futtermittelgesetzbuch" },
	KSchG: { title: "K\u00fcndigungsschutzgesetz" },
	KWGWpIGVermV: { title: "KWG-WpIG-Vermittlerverordnung" },
	KrWG: { title: "Kreislaufwirtschaftsgesetz" },
	KSpG: { title: "Kohlendioxid-Speicherungsgesetz" },
	LiqV: { title: "Liquidit\u00e4tsverordnung" },
	KWKAusV: { title: "KWK-Ausschreibungsverordnung" },
	LMHV: { title: "Lebensmittelhygiene-Verordnung" },
	LkSG: { title: "Lieferkettensorgfaltspflichtengesetz" },
	KWKG: { title: "Kraft-W\u00e4rme-Kopplungsgesetz" },
	KStG: { title: "K\u00f6rperschaftsteuergesetz" },
	LMIDV: { title: "Lebensmittelinformations-Durchf\u00fchrungsverordnung" },
	LKV: { title: "Los-Kennzeichnungs-Verordnung" },
	KTFG: { title: "Klima- und Transformationsfondsgesetz" },
	LPartG: { title: "Lebenspartnerschaftsgesetz" },
	"LMRStV 2006": { title: "Lebensmittel-Straf- und Bu\u00dfgeldverordnung" },
	LSV: { title: "Lades\u00e4ulenverordnung" },
	LNGG: { title: "LNG-Beschleunigungsgesetz" },
	MaBV: { title: "Makler- und Bautr\u00e4gerverordnung" },
	LNGV: { title: "LNG-Verordnung" },
	MitbestG: { title: "Mitbestimmungsgesetz" },
	MuSchG: { title: "Mutterschutzgesetz" },
	MarkenG: { title: "Markengesetz" },
	LobbyRG: { title: "Lobbyregistergesetz" },
	MontanMitbestG: { title: "Montan-Mitbestimmungsgesetz" },
	MarkenV: { title: "Markenverordnung" },
	MontanMitbestGErgG: {
		title: "Montan-Mitbestimmungsgesetz-Erg\u00e4nzungsgesetz",
	},
	"M\u00fcG": { title: "Markt\u00fcberwachungsgesetz" },
	NABEG: { title: "Netzausbaubeschleunigungsgesetz \u00dcbertragungsnetz" },
	MessEG: { title: "Mess- und Eichgesetz" },
	MPG: { title: "Medizinproduktegesetz" },
	NetzResV: { title: "Netzreserveverordnung" },
	NachwG: { title: "Nachweisgesetz" },
	MsbG: { title: "Messstellenbetriebsgesetz" },
	NiSG: {
		title: "Gesetz zum Schutz vor nichtionisierender Strahlung bei der Anwendung am Menschen",
	},
	NemV: { title: "Nahrungserg\u00e4nzungsmittelverordnung" },
	MgFSG: {
		title: "Gesetz \u00fcber die Mitbestimmung der Arbeitnehmer bei grenz\u00fcberschreitendem Formwechsel und grenz\u00fcberschreitender Spaltung",
	},
	MuSchEltZV: { title: "Mutterschutz- und Elternzeitverordnung" },
	NotAktVV: {
		title: "Verordnung \u00fcber die F\u00fchrung notarieller Akten und Verzeichnisse",
	},
	OEG: { title: "Opferentsch\u00e4digungsgesetz" },
	NetzDG: { title: "Netzwerkdurchsetzungsgesetz" },
	OWiG: { title: "Gesetz \u00fcber Ordnungswidrigkeiten" },
	NotViKoV: {
		title: "Verordnung \u00fcber den Betrieb eines Videokommunikationssystems f\u00fcr notarielle Urkundst\u00e4tigkeiten",
	},
	MietRVerbG: { title: "Mietrechtsverbesserungsgesetz" },
	OZG: { title: "Onlinezugangsgesetz" },
	PflSchG: { title: "Pflanzenschutzgesetz" },
	PKGrG: { title: "Kontrollgremiumgesetz" },
	MiLoG: { title: "Mindestlohngesetz" },
	PAngV: { title: "Preisangabenverordnung" },
	PlanZV: { title: "Planzeichenverordnung" },
	PflVG: { title: "Pflichtversicherungsgesetz" },
	OASG: { title: "Opferanspruchssicherungsgesetz" },
	PrKG: { title: "Preisklauselgesetz" },
	PAO: { title: "Patentanwaltsordnung" },
	ProdHaftG: { title: "Produkthaftungsgesetz" },
	"Pf\u00e4ndfreiGrBek 2021": {
		title: "Pf\u00e4ndungsfreigrenzenbekanntmachung 2021",
	},
	PStTG: { title: "Plattformen-Steuertransparenzgesetz" },
	PartG: { title: "Parteiengesetz" },
	"Pf\u00e4ndfreiGrBek 2022": {
		title: "Pf\u00e4ndungsfreigrenzenbekanntmachung 2022",
	},
	MiLoV4: { title: "Vierte Mindestlohnanpassungsverordnung" },
	ProdSG: { title: "Produktsicherheitsgesetz" },
	"Pf\u00e4ndungsfreigrenzenbekanntmachung 2023": {
		title: "Bekanntmachung zu den Pf\u00e4ndungsfreigrenzen 2023 nach \u00a7 850c der Zivilprozessordnung",
	},
	PUAG: { title: "Untersuchungsausschussgesetz" },
	PStG: { title: "Personenstandsgesetz" },
	MinStG: { title: "Mindeststeuergesetz" },
	PublG: { title: "Publizit\u00e4tsgesetz" },
	RAVPV: { title: "Rechtsanwaltsverzeichnis- und -postfachverordnung" },
	RechKredV: { title: "Kreditinstituts-Rechnungslegungsverordnung" },
	RDG: { title: "Rechtsdienstleistungsgesetz" },
	RiWG: { title: "Richterwahlgesetz" },
	ROG: { title: "Raumordnungsgesetz" },
	SchuFV: { title: "Schuldnerverzeichnisf\u00fchrungsverordnung" },
	RDV: { title: "Rechtsdienstleistungsverordnung" },
	"SGB II": { title: "Grundsicherung f\u00fcr Arbeitsuchende" },
	SchuVAbdrV: { title: "Schuldnerverzeichnisabdruckverordnung" },
	RStruktFG: { title: "Restrukturierungsfondsgesetz" },
	"SGB III": { title: "Arbeitsf\u00f6rderung" },
	"SGB VII": { title: "Gesetzliche Unfallversicherung" },
	RPflG: { title: "Rechtspflegergesetz" },
	"Rom-I-VO": { title: "Rom-I-Verordnung" },
	"Rom-II-VO": { title: "Rom-II-Verordnung" },
	SchVG: { title: "Schuldverschreibungsgesetz" },
	"SGB IV": {
		title: "Gemeinsame Vorschriften f\u00fcr die Sozialversicherung",
	},
	RVG: { title: "Rechtsanwaltsverg\u00fctungsgesetz" },
	SchwarzArbG: { title: "Schwarzarbeitsbek\u00e4mpfungsgesetz" },
	"SGB IX": {
		title: "Rehabilitation und Teilhabe von Menschen mit Behinderungen",
	},
	"SGB VIII": { title: "Kinder- und Jugendhilfe" },
	SAG: { title: "Sanierungs- und Abwicklungsgesetz" },
	SolvV: { title: "Solvabilit\u00e4tsverordnung" },
	SektVO: { title: "Sektorenverordnung" },
	"SGB V": { title: "Gesetzliche Krankenversicherung" },
	"SGB X": { title: "Sozialverwaltungsverfahren und Sozialdatenschutz" },
	SpaEfV: { title: "Spitzenausgleich-Effizienzsystemverordnung" },
	"SGB VI": { title: "Gesetzliche Rentenversicherung" },
	"SGB I": { title: "Allgemeiner Teil" },
	SanktDG: { title: "Sanktionsdurchsetzungsgesetz" },
	"SGB XI": { title: "Soziale Pflegeversicherung" },
	SprengG: { title: "Sprengstoffgesetz" },
	SchadRegProtAG: {
		title: "Schadstofregister-Protokoll-Ausf\u00fchrungsgesetz",
	},
	SpruchG: { title: "Spruchverfahrensgesetz" },
	"SGB XII": { title: "Sozialhilfe" },
	PartGG: { title: "Partnerschaftsgesellschaftsgesetz" },
	"Schl\u00e4rmschG": { title: "Schienenl\u00e4rmschutzgesetz" },
	"SStellV-VVG": { title: "VVG-Schlichtungsstellenverordnung" },
	SGG: { title: "Sozialgerichtsgesetz" },
	StabiRatG: { title: "Stabilit\u00e4tsratsgesetz" },
	StAbwG: { title: "Steueroasen-Abwehrgesetz" },
	StFG: { title: "Stabilisierungsfondsgesetz" },
	PatG: { title: "Patentgesetz" },
	StAG: { title: "Staatsangeh\u00f6rigkeitsgesetz" },
	StGB: { title: "Strafgesetzbuch" },
	StromPBG: { title: "Strompreisbremsegesetz" },
	StZG: { title: "Stammzellgesetz" },
	StandAG: { title: "Standortauswahlgesetz" },
	StromStG: { title: "Stromsteuergesetz" },
	TEHG: { title: "Treibhausgas-Emissionshandelsgesetz" },
	SubvG: { title: "Subventionsgesetz" },
	StiftFinG: { title: "Stiftungsfinanzierungsgesetz" },
	SUrlV: { title: "Sonderurlaubsverordnung" },
	StromStV: { title: "Stromsteuer-Durchf\u00fchrungsverordnung" },
	StiftRG: { title: "Stiftungsregistergesetz" },
	SysStabV: { title: "Systemstabilit\u00e4tsverordnung" },
	StVG: { title: "Stra\u00dfenverkehrsgesetz" },
	TFG: { title: "Transfusionsgesetz" },
	StaRUG: {
		title: "Unternehmensstabilisierungs- und -restrukturierungsgesetz",
	},
	"S\u00dcG": { title: "Sicherheits\u00fcberpr\u00fcfungsgesetz" },
	StPO: { title: "Strafprozessordnung" },
	StVO: { title: "Stra\u00dfenverkehrs-Ordnung" },
	TGV: { title: "Trennungsgeldverordnung" },
	PBefG: { title: "Personenbef\u00f6rderungsgesetz" },
	TDDDG: { title: "Telekommunikation-Digitale-Dienste-Datenschutz-Gesetz" },
	StrEG: {
		title: "Gesetz \u00fcber die Entsch\u00e4digung f\u00fcr Strafverfolgungsma\u00dfnahmen",
	},
	StVZO: { title: "Stra\u00dfenverkehrs-Zulassungs-Ordnung" },
	TierHaltKennzG: { title: "Tierhaltungskennzeichnungsgesetz" },
	StBerG: { title: "Steuerberatungsgesetz" },
	TierSchG: { title: "Tierschutzgesetz" },
	StBVV: { title: "Steuerberaterverg\u00fctungsverordnung" },
	TzBfG: { title: "Teilzeit- und Befristungsgesetz" },
	"TK\u00dcV": { title: "Telekommunikations-\u00dcberwachungsverordnung" },
	UKlaG: { title: "Unterlassungsklagengesetz" },
	TKG: { title: "Telekommunikationsgesetz" },
	UAG: { title: "Umweltauditgesetz" },
	UmweltHG: { title: "Umwelthaftungsgesetz" },
	TMG: { title: "Telemediengesetz" },
	UBAG: { title: "Gesetz \u00fcber die Errichtung eines Umweltbundesamtes" },
	TPG: { title: "Transplantationsgesetz" },
	UmwG: { title: "Umwandlungsgesetz" },
	UBGG: { title: "Gesetz \u00fcber Unternehmensbeteiligungsgesellschaften" },
	PfandBG: { title: "Pfandbriefgesetz" },
	UmwRG: { title: "Umwelt-Rechtsbehelfsgesetz" },
	UStatG: { title: "Umweltstatistikgesetz" },
	TSG: { title: "Transsexuellengesetz" },
	UhVorschG: { title: "Unterhaltsvorschussgesetz" },
	TTDSG: { title: "Telekommunikation-Telemedien-Datenschutz-Gesetz" },
	UIG: { title: "Umweltinformationsgesetz" },
	"UmwStG 1995": { title: "Umwandlungssteuergesetz 1995" },
	UStDV: { title: "Umsatzsteuer-Durchf\u00fchrungsverordnung" },
	PflegeZG: { title: "Pflegezeitgesetz" },
	TVG: { title: "Tarifvertragsgesetz" },
	"UmwStG 2006": { title: "Umwandlungssteuergesetz 2006" },
	UrhG: { title: "Urheberrechtsgesetz" },
	UStG: { title: "Umsatzsteuergesetz" },
	VAG: { title: "Versicherungsaufsichtsgesetz" },
	USchadG: { title: "Umweltschadensgesetz" },
	VersVermV: { title: "Versicherungsvermittlungsverordnung" },
	VermAnlG: { title: "Verm\u00f6gensanlagengesetz" },
	VBVG: { title: "Vorm\u00fcnder- und Betreuerverg\u00fctungsgesetz" },
	UVPG: {
		title: "Gesetz \u00fcber die Umweltvertr\u00e4glichkeitspr\u00fcfung",
	},
	VGG: { title: "Verwertungsgesellschaftengesetz" },
	VermVV: { title: "Verm\u00f6gensverzeichnisverordnung" },
	VDG: { title: "Vertrauensdienstegesetz" },
	VDuG: { title: "Verbraucherrechtedurchsetzungsgesetz" },
	UWG: { title: "Gesetz gegen den unlauteren Wettbewerb" },
	VerpackG: { title: "Verpackungsgesetz" },
	WaffG: { title: "Waffengesetz" },
	VgV: { title: "Vergabeverordnung" },
	VereinsG: { title: "Vereinsgesetz" },
	WaffRG: { title: "Waffenregistergesetz" },
	VIG: { title: "Verbraucherinformationsgesetz" },
	"\u00dcAnlG": {
		title: "Gesetz \u00fcber \u00fcberwachungsbed\u00fcrftige Anlagen",
	},
	VersAusglG: { title: "Versorgungsausgleichsgesetz" },
	VergStatVO: { title: "Vergabestatistikverordnung" },
	WaffRGDV: { title: "Waffenregistergesetz-Durchf\u00fchrungsverordnung" },
	VkBkmG: { title: "Verk\u00fcndungs- und Bekanntmachungsgesetz" },
	VSVgV: { title: "Vergabenverordnung Verteidigung und Sicherheit" },
	WahlPrG: { title: "Wahlpr\u00fcfungsgesetz" },
	"VersStG 2021": { title: "Versicherungsteuergesetz" },
	WHG: { title: "Wasserhaushaltsgesetz" },
	WBVG: { title: "Wohn- und Betreuungsvertragsgesetz" },
	WoFlV: { title: "Wohnfl\u00e4chenverordnung" },
	WEG: { title: "Wohnungseigentumsgesetz" },
	WindBG: { title: "Windenergiefl\u00e4chenbedarfsgesetz" },
	WoVermRG: { title: "Gesetz zur Regelung der Wohnungsvermittlung" },
	VersVergV: { title: "Versicherungs-Verg\u00fctungsverordnung" },
	WindSeeG: { title: "Windenergie-auf-See-Gesetz" },
	WPG: { title: "W\u00e4rmeplanungsgesetz" },
	"Wp\u00dcG": { title: "Wertpapiererwerbs- und \u00dcbernahmegesetz" },
	WiStrG: { title: "Wirtschaftsstrafgesetz 1954" },
	WpHG: { title: "Wertpapierhandelsgesetz" },
	ZPOEG: {
		title: "Gesetz, betreffend die Einf\u00fchrung der Zivilproze\u00dfordnung",
	},
	ZAG: { title: "Zahlungsdiensteaufsichtsgesetz" },
	WoBindG: { title: "Wohnungsbindungsgesetz" },
	WpIG: { title: "Wertpapierinstitutsgesetz" },
	"Wp\u00dcGAngebV": { title: "Wp\u00dcG-Angebotsverordnung" },
	ZHG: { title: "Gesetz \u00fcber die Aus\u00fcbung der Zahnheilkunde" },
	WoFG: { title: "Wohnraumf\u00f6rderungsgesetz" },
	WRegG: { title: "Wettbewerbsregistergesetz" },
	WPO: { title: "Wirtschaftspr\u00fcferordnung" },
	ZVG: {
		title: "Gesetz \u00fcber die Zwangsversteigerung und die Zwangsverwaltung",
	},
	WRMG: { title: "Wasch- und Reinigungsmittelgesetz" },
	"ZIdPr\u00fcfV": {
		title: "Zahlungskonto-Identit\u00e4tspr\u00fcfungsverordnung",
	},
	"1. BImSchV": {
		title: "Verordnung \u00fcber kleine und mittlere Feuerungsanlagen",
	},
	ZKDSG: { title: "Zugangskontrolldiensteschutz-Gesetz" },
	WRV: { title: "Die Verfassung des Deutschen Reichs" },
	"11. BImSchV": {
		title: "Elfte Verordnung zur Durchf\u00fchrung des Bundes-Immissionsschutzgesetzes (Verordnung \u00fcber Emissionserkl\u00e4rungen)",
	},
	"1. ProdSV": { title: "Verordnung \u00fcber elektrische Betriebsmittel" },
	"11. ProdSV": { title: "Explosionsschutzprodukteverordnung" },
	WStG: { title: "Wehrstrafgesetz" },
	ZollVG: { title: "Zollverwaltungsgesetz" },
	"14. BImSchV": {
		title: "Verordnung \u00fcber Anlagen der Landesverteidigung",
	},
	"10. BImSchV": {
		title: "Verordnung \u00fcber die Beschaffenheit und die Auszeichnung der Qualit\u00e4ten von Kraft- und Brennstoffen",
	},
	"12. BImSchV": { title: "St\u00f6rfall-Verordnung" },
	"14. ProdSV": { title: "Druckger\u00e4teverordnung" },
	"12. ProdSV": { title: "Aufzugsverordnung" },
	ZPO: { title: "Zivilprozessordnung" },
	"10. ProdSV": {
		title: "Verordnung \u00fcber Sportboote und Wassermotorr\u00e4der",
	},
	"2. ProdSV": { title: "Verordnung \u00fcber die Sicherheit von Spielzeug" },
	"13. BImSchV": {
		title: "Verordnung \u00fcber Gro\u00dffeuerungs-, Gasturbinen- und Verbrennungsmotoranlagen",
	},
	"16. BImSchV": { title: "Verkehrsl\u00e4rmschutzverordnung" },
	"13. ProdSV": { title: "Aerosolpackungsverordnung" },
	"20. BImSchV": {
		title: "Verordnung zur Begrenzung der Emissionen fl\u00fcchtiger organischer Verbindungen beim Umf\u00fcllen oder Lagern von Ottokraftstoffen, Kraftstoffgemischen oder Rohbenzin",
	},
	"17. BImSchV": {
		title: "Verordnung \u00fcber die Verbrennung und die Mitverbrennung von Abf\u00e4llen",
	},
	"21. BImSchV": {
		title: "Verordnung zur Begrenzung der Kohlenwasserstoffemissionen bei der Betankung von Kraftfahrzeugen",
	},
	"27. BImSchV": {
		title: "Verordnung \u00fcber Anlagen zur Feuerbestattung",
	},
	"34. BImSchV": { title: "Verordnung \u00fcber die L\u00e4rmkartierung" },
	"24. BImSchV": {
		title: "Verkehrswege-Schallschutzma\u00dfnahmenverordnung",
	},
	"35. BImSchV": {
		title: "Verordnung zur Kennzeichnung der Kraftfahrzeuge mit geringem Beitrag zur Schadstoffbelastung",
	},
	"25. BImSchV": {
		title: "Verordnung zur Begrenzung von Emissionen aus der Titandioxid-Industrie",
	},
	"28. BImSchV": {
		title: "Verordnung zur Durchf\u00fchrung der unionsrechtlichen Verordnung \u00fcber Emissionsgrenzwerte und die Typgenehmigung f\u00fcr Verbrennungsmotoren f\u00fcr nicht f\u00fcr den Stra\u00dfenverkehr bestimmte mobile Maschinen und Ger\u00e4te",
	},
	"18. BImSchV": { title: "Sportanlagenl\u00e4rmschutzverordnung" },
	"26. BImSchV": { title: "Verordnung \u00fcber elektromagnetische Felder" },
	"36. BImSchV": {
		title: "Verordnung zur Durchf\u00fchrung der Regelungen der Biokraftstoffquote",
	},
	"29. BImSchV": {
		title: "Geb\u00fchrenordnung f\u00fcr Ma\u00dfnahmen bei Typpr\u00fcfungen von Verbrennungsmotoren",
	},
	"2. BImSchV": {
		title: "Verordnung zur Emissionsbegrenzung von leichtfl\u00fcchtigen halogenierten organischen Verbindungen",
	},
	"37. BImSchV": {
		title: "Verordnung zur Anrechnung von strombasierten Kraftstoffen und mitverarbeiteten biogenen \u00d6len auf die Treibhausgasquote",
	},
	"30. BImSchV": {
		title: "Verordnung \u00fcber Anlagen zur biologischen Behandlung von Abf\u00e4llen",
	},
	"38. BImSchV": {
		title: "Verordnung zur Festlegung weiterer Bestimmungen zur Treibhausgasminderung bei Kraftstoffen",
	},
	"6. ProdSV": { title: "Verordnung \u00fcber einfache Druckbeh\u00e4lter" },
	"31. BImSchV": {
		title: "Verordnung zur Begrenzung der Emissionen fl\u00fcchtiger organischer Verbindungen bei der Verwendung organischer L\u00f6semittel in bestimmten Anlagen",
	},
	"7. BImSchV": { title: "Verordnung zur Auswurfbegrenzung von Holzstaub" },
	"39. BImSchV": {
		title: "Verordnung \u00fcber Luftqualit\u00e4tsstandards und Emissionsh\u00f6chstmengen",
	},
	"32. BImSchV": {
		title: "Ger\u00e4te- und Maschinenl\u00e4rmschutzverordnung",
	},
	"9. BImSchV": { title: "Verordnung \u00fcber das Genehmigungsverfahren" },
	"9. ProdSV": {
		title: "Neunte Verordnung zum Produktsicherheitsgesetz (Maschinenverordnung)",
	},
	"4. BImSchV": {
		title: "Verordnung \u00fcber genehmigungsbed\u00fcrftige Anlagen",
	},
	"41. BImSchV": { title: "Bekanntgabeverordnung" },
	"42. BImSchV": {
		title: "Verordnung \u00fcber Verdunstungsk\u00fchlanlagen, K\u00fchlt\u00fcrme und Nassabscheider",
	},
	"43. BImSchV": {
		title: "Verordnung \u00fcber nationale Verpflichtungen zur Reduktion der Emissionen bestimmter Luftschadstoffe",
	},
	"44. BImSchV": {
		title: "Verordnung \u00fcber mittelgro\u00dfe Feuerungs-, Gasturbinen- und Verbrennungsmotoranlagen",
	},
	"5. BImSchV": {
		title: "Verordnung \u00fcber Immissionsschutz- und St\u00f6rfallbeauftragte",
	},
	VVG: { title: "Versicherungsvertragsgesetz" },
	"VVG-InfoV": { title: "VVG-Informationspflichtenverordnung" },
	VwGO: { title: "Verwaltungsgerichtsordnung" },
	VwVfG: { title: "Verwaltungsverfahrensgesetz" },
	VwVG: { title: "Verwaltungs-Vollstreckungsgesetz" },
	VwZG: { title: "Verwaltungszustellungsgesetz" },
};

export const lexmeaGesetzeLowerCased = Object.keys(lexmeaGesetze).map((key) =>
	key.toLowerCase()
);
